typography_spectrum: 0.49870334030129015
content_rating:
  adult: false
color:
  brandStrength: 0.8676291592419147
  lightness: 0.23106679343618453
  saturation: 0.3197845409158617
  rhythmicContrast: 0.6688940017484128
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
layout_spectrum: 0.009792670607566833
name: Pastor Dillon Evans
navigation:
  - name: About Me
    id: bfc3fdd1-537f-43db-b160-64753cd1cd90
    type: content
  - name: Help with Websites
    id: fb9d2e81-30a6-4ac2-8ac8-521530500083
    type: content
title: Itâ€™s always about the Gospel of Christ
description: Radical Follower of the Way
